add equivs package
The workflow gave the following error:
  mk-build-deps: You must have equivs installed to use this program.
  Error: Process completed with exit code 127.
So equivs package is added as dependency.

Changes to be committed:
	modified:   .github/workflows/build_debian_package.yml